/* Generated By:JavaCC: Do not edit this line. adderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface adderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int NUMTYPES = 9;
  /** RegularExpression Id. */
  int FLOATTYPE = 10;
  /** RegularExpression Id. */
  int BOOLTYPE = 11;
  /** RegularExpression Id. */
  int PROGRAM = 12;
  /** RegularExpression Id. */
  int MAIN = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int LBRACE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int WHILE = 21;
  /** RegularExpression Id. */
  int EQUALS = 22;
  /** RegularExpression Id. */
  int SUM = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int MULT = 25;
  /** RegularExpression Id. */
  int DIVIDE = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int SAMEAS = 29;
  /** RegularExpression Id. */
  int GREATER = 30;
  /** RegularExpression Id. */
  int LESSER = 31;
  /** RegularExpression Id. */
  int GREATSAME = 32;
  /** RegularExpression Id. */
  int LESSAME = 33;
  /** RegularExpression Id. */
  int DIFFERENT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<IDENTIFIER>",
    "<STRING>",
    "<NUMBER>",
    "<NUMTYPES>",
    "<FLOATTYPE>",
    "<BOOLTYPE>",
    "\"program \"",
    "\"public static void main() \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"for \"",
    "\"do \"",
    "\"while \"",
    "\"= \"",
    "\"+ \"",
    "\"- \"",
    "\"* \"",
    "\"/ \"",
    "<AND>",
    "<OR>",
    "\"== \"",
    "\"> \"",
    "\"< \"",
    "\">= \"",
    "\"<= \"",
    "\"<> \"",
  };

}
